In [1]:
# -----import excel file-----

In [2]:
import pandas as pd
df_cars=pd.read_csv(r"C:\jayasri\car_project\CarPrice_Assignment.csv")
df_cars

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [3]:
# df_cars.cylindernumber.unique()

In [4]:
# ---------basic checks------

In [5]:
df_cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [6]:
df_cars.tail()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [7]:
df_cars.shape

(205, 26)

In [8]:
df_cars.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [9]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [10]:
df_cars.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [11]:
type(df_cars)

pandas.core.frame.DataFrame

In [12]:
df_cars.index

RangeIndex(start=0, stop=205, step=1)

In [13]:
#---using isnull ------

In [14]:
df_cars.isnull()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
#----using fillna----

In [16]:
df_cars.fillna(0)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [17]:
df_cars.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [18]:
df_cars.cylindernumber.unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [19]:
#-----1-----select only bmw, audi,nissan-----------------------

In [20]:
df_car_po=df_cars[df_cars["CarName"].isin(['bmw 320i','bmw x1','bmw x2','b mw x3','bmw x4','bmw z4','bmw x5','audi 100 ls','audi 100ls','audi fox','audi 5000','audi 4000','audi 5000s (diesel)','Nissan versa','nissan gt-r','nissan rogue','nissan latio','nissan titan','nissan leaf','nissan juke','nissan latio','nissan note','nissan clipper','nissan rogue','nissan nv200','nissan dayz','nissan fuga','nissan otti','nissan teana','nissan kicks','nissan clipper'])]

In [21]:
df_car_po

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
14,15,1,bmw z4,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,17,0,bmw x5,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
89,90,1,Nissan versa,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499.000
90,91,1,nissan gt-r,diesel,std,two,sedan,fwd,front,94.5,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099.000
91,92,1,nissan rogue,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6649.000
92,93,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849.000
93,94,1,nissan titan,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7349.000
94,95,1,nissan leaf,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7299.000
95,96,1,nissan juke,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799.000
96,97,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499.000
97,98,1,nissan note,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999.000
98,99,2,nissan clipper,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249.000
99,100,0,nissan rogue,gas,std,four,hatchback,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949.000
100,101,0,nissan nv200,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549.000
101,102,0,nissan dayz,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499.000
102,103,0,nissan fuga,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399.000
103,104,0,nissan otti,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499.000
104,105,3,nissan teana,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199.000
105,106,3,nissan kicks,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699.000
106,107,1,nissan clipper,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399.000

In [22]:
df_car_proj=pd.DataFrame(df_car_po)

In [23]:
df_car_proj

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
14,15,1,bmw z4,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,17,0,bmw x5,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
89,90,1,Nissan versa,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499.000
90,91,1,nissan gt-r,diesel,std,two,sedan,fwd,front,94.5,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099.000
91,92,1,nissan rogue,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6649.000
92,93,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849.000
93,94,1,nissan titan,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7349.000
94,95,1,nissan leaf,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7299.000
95,96,1,nissan juke,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799.000
96,97,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499.000
97,98,1,nissan note,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999.000
98,99,2,nissan clipper,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249.000
99,100,0,nissan rogue,gas,std,four,hatchback,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949.000
100,101,0,nissan nv200,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549.000
101,102,0,nissan dayz,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499.000
102,103,0,nissan fuga,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399.000
103,104,0,nissan otti,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499.000
104,105,3,nissan teana,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199.000
105,106,3,nissan kicks,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699.000
106,107,1,nissan clipper,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399.000

In [24]:
#----****** output storing into excel file ------

In [25]:

# df_car_proj.to_excel(r"C:\jayasri\car_output.xlsx",index=False)

In [26]:
df_car_proj.cylindernumber.unique()

array(['four', 'five', 'six'], dtype=object)

In [27]:
#---2------overall price----------

In [28]:
df_car_proj[["CarName","price"]]

                 CarName      price
3            audi 100 ls  13950.000
4             audi 100ls  17450.000
5               audi fox  15250.000
6             audi 100ls  17710.000
7              audi 5000  18920.000
8              audi 4000  23875.000
9    audi 5000s (diesel)  17859.167
10              bmw 320i  16430.000
11              bmw 320i  16925.000
12                bmw x1  20970.000
14                bmw z4  24565.000
15                bmw x4  30760.000
16                bmw x5  41315.000
89          Nissan versa   5499.000
90           nissan gt-r   7099.000
91          nissan rogue   6649.000
92          nissan latio   6849.000
93          nissan titan   7349.000
94           nissan leaf   7299.000
95           nissan juke   7799.000
96          nissan latio   7499.000
97           nissan note   7999.000
98        nissan clipper   8249.000
99          nissan rogue   8949.000
100         nissan nv200   9549.000
101          nissan dayz  13499.000
102          nissan fuga  14399.000
103          nissan otti  13499.000
104         nissan teana  17199.000
105         nissan kicks  19699.000
106       nissan clipper  18399.000

In [29]:
#--3----fuel_system $ price

In [30]:
df_car_proj[['fuelsystem','price']]

    fuelsystem      price
3         mpfi  13950.000
4         mpfi  17450.000
5         mpfi  15250.000
6         mpfi  17710.000
7         mpfi  18920.000
8         mpfi  23875.000
9         mpfi  17859.167
10        mpfi  16430.000
11        mpfi  16925.000
12        mpfi  20970.000
14        mpfi  24565.000
15        mpfi  30760.000
16        mpfi  41315.000
89        2bbl   5499.000
90         idi   7099.000
91        2bbl   6649.000
92        2bbl   6849.000
93        2bbl   7349.000
94        2bbl   7299.000
95        2bbl   7799.000
96        2bbl   7499.000
97        2bbl   7999.000
98        2bbl   8249.000
99        2bbl   8949.000
100       2bbl   9549.000
101       mpfi  13499.000
102       mpfi  14399.000
103       mpfi  13499.000
104       mpfi  17199.000
105       mpfi  19699.000
106       mpfi  18399.000

In [31]:
#-4---car body , fuel_system $ price

In [32]:
df_car_proj[['carbody','fuelsystem','price']]

       carbody fuelsystem      price
3        sedan       mpfi  13950.000
4        sedan       mpfi  17450.000
5        sedan       mpfi  15250.000
6        sedan       mpfi  17710.000
7        wagon       mpfi  18920.000
8        sedan       mpfi  23875.000
9    hatchback       mpfi  17859.167
10       sedan       mpfi  16430.000
11       sedan       mpfi  16925.000
12       sedan       mpfi  20970.000
14       sedan       mpfi  24565.000
15       sedan       mpfi  30760.000
16       sedan       mpfi  41315.000
89       sedan       2bbl   5499.000
90       sedan        idi   7099.000
91       sedan       2bbl   6649.000
92       sedan       2bbl   6849.000
93       wagon       2bbl   7349.000
94       sedan       2bbl   7299.000
95   hatchback       2bbl   7799.000
96       sedan       2bbl   7499.000
97       wagon       2bbl   7999.000
98     hardtop       2bbl   8249.000
99   hatchback       2bbl   8949.000
100      sedan       2bbl   9549.000
101      sedan       mpfi  13499.000
102      wagon       mpfi  14399.000
103      sedan       mpfi  13499.000
104  hatchback       mpfi  17199.000
105  hatchback       mpfi  19699.000
106  hatchback       mpfi  18399.000

In [33]:
#--5---		carbody	fuelsystem 	compressionratio-overall	horsepower-overall	peakrpm-overall	citympg-overall	highwaympg-overall	price-overall

In [34]:
df_car_proj.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [35]:
df_car_proj[['carbody','fuelsystem','compressionratio','horsepower','peakrpm','citympg','highwaympg','price']]

,carbody,fuelsystem,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,sedan,mpfi,10.0,102,5500,24,30,13950.000
4,sedan,mpfi,8.0,115,5500,18,22,17450.000
5,sedan,mpfi,8.5,110,5500,19,25,15250.000
6,sedan,mpfi,8.5,110,5500,19,25,17710.000
7,wagon,mpfi,8.5,110,5500,19,25,18920.000
8,sedan,mpfi,8.3,140,5500,17,20,23875.000
9,hatchback,mpfi,7.0,160,5500,16,22,17859.167
10,sedan,mpfi,8.8,101,5800,23,29,16430.000
11,sedan,mpfi,8.8,101,5800,23,29,16925.000
12,sedan,mpfi,9.0,121,4250,21,28,20970.000
14,sedan,mpfi,9.0,121,4250,20,25,24565.000
15,sedan,mpfi,8.0,182,5400,16,22,30760.000
16,sedan,mpfi,8.0,182,5400,16,22,41315.000
89,sedan,2bbl,9.4,69,5200,31,37,5499.000
90,sedan,idi,21.9,55,4800,45,50,7099.000
91,sedan,2bbl,9.4,69,5200,31,37,6649.000
92,sedan,2bbl,9.4,69,5200,31,37,6849.000
93,wagon,2bbl,9.4,69,5200,31,37,7349.000
94,sedan,2bbl,9.4,69,5200,31,37,7299.000
95,hatchback,2bbl,9.4,69,5200,31,37,7799.000
96,sedan,2bbl,9.4,69,5200,31,37,7499.000
97,wagon,2bbl,9.4,69,5200,31,37,7999.000
98,hardtop,2bbl,9.4,69,5200,31,37,8249.000
99,hatchback,2bbl,8.5,97,5200,27,34,8949.000
100,sedan,2bbl,8.5,97,5200,27,34,9549.000
101,sedan,mpfi,9.0,152,5200,17,22,13499.000
102,wagon,mpfi,9.0,152,5200,17,22,14399.000
103,sedan,mpfi,9.0,152,5200,19,25,13499.000
104,hatchback,mpfi,9.0,160,5200,19,25,17199.000
105,hatchback,mpfi,7.8,200,5200,17,23,19699.000
106,hatchback,mpfi,9.0,160,5200,19,25,18399.000

In [36]:
#----6----			enginetype	cylindernumber	enginesize	fuelsystem	boreratio	stroke	compressionratio	horsepower	peakrpm	citympg	highwaympg	price

In [37]:
df_car_proj.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [38]:
df_car_proj[['enginetype','cylindernumber','enginesize','fuelsystem','boreratio','stroke','compressionratio','horsepower','peakrpm','citympg','highwaympg','price']]

,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
14,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
89,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499.000
90,ohc,four,103,idi,2.99,3.47,21.9,55,4800,45,50,7099.000
91,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6649.000
92,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849.000
93,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7349.000
94,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7299.000
95,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799.000
96,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499.000
97,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999.000
98,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249.000
99,ohc,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949.000
100,ohc,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549.000
101,ohcv,six,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499.000
102,ohcv,six,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399.000
103,ohcv,six,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499.000
104,ohcv,six,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199.000
105,ohcv,six,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699.000
106,ohcv,six,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399.000

In [39]:
df_car_proj.cylindernumber.unique()

array(['four', 'five', 'six'], dtype=object)

In [40]:
#--***  7--A-----select only combination of enginetype ohc and cylindernumber one,two,three,four,five,six
# 			enginetype	cylindernumber	enginesize	fuelsystem	boreratio	stroke	compressionratio	horsepower	peakrpm	citympg	highwaympg	price

In [41]:
# df = df[df[['team', 'position']].isin(['A', 'Guard']).all(axis=1)]

In [42]:
df_eng_cyl=df_car_proj[df_car_proj[['cylindernumber','enginetype']].isin(['one','two','three','four','five','six','ohc']).all(axis=1)]
df_eng_cyl

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
14,15,1,bmw z4,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,17,0,bmw x5,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
89,90,1,Nissan versa,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499.000
90,91,1,nissan gt-r,diesel,std,two,sedan,fwd,front,94.5,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099.000
91,92,1,nissan rogue,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6649.000
92,93,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849.000
93,94,1,nissan titan,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7349.000
94,95,1,nissan leaf,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7299.000
95,96,1,nissan juke,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799.000
96,97,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499.000
97,98,1,nissan note,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999.000
98,99,2,nissan clipper,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249.000
99,100,0,nissan rogue,gas,std,four,hatchback,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949.000
100,101,0,nissan nv200,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549.000

In [43]:
df_eng_cyl.enginetype.unique()

array(['ohc'], dtype=object)

In [44]:
df_eng_cyl.cylindernumber.unique()

array(['four', 'five', 'six'], dtype=object)

In [45]:
df_eng_cyl[['enginetype','cylindernumber','enginesize','fuelsystem','boreratio','stroke','compressionratio','horsepower','peakrpm','citympg','highwaympg','price']]

,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,ohc,five,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,ohc,five,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,ohc,four,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
14,ohc,six,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,ohc,six,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
89,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499.000
90,ohc,four,103,idi,2.99,3.47,21.9,55,4800,45,50,7099.000
91,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6649.000
92,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849.000
93,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7349.000
94,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7299.000
95,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799.000
96,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499.000
97,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999.000
98,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249.000
99,ohc,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949.000
100,ohc,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549.000

In [46]:
df_eng_cyl.cylindernumber.unique()

array(['four', 'five', 'six'], dtype=object)

In [47]:
#-----7-----B------select only combination of enginetype ohc and cylindernumber one

In [48]:
df1=df_car_proj[(df_car_proj['enginetype']=='ohc') & (df_car_proj['cylindernumber']=='one')]
df1

Empty DataFrame
Columns: [car_ID, symboling, CarName, fueltype, aspiration, doornumber, carbody, drivewheel, enginelocation, wheelbase, carlength, carwidth, carheight, curbweight, enginetype, cylindernumber, enginesize, fuelsystem, boreratio, stroke, compressionratio, horsepower, peakrpm, citympg, highwaympg, price]
Index: []

[0 rows x 26 columns]

In [49]:
df1.cylindernumber.unique

In [50]:
#  			enginetype	cylindernumber	enginesize	fuelsystem	boreratio	stroke	compressionratio	horsepower	peakrpm	citympg	highwaympg	price

In [51]:
df1[['enginetype','cylindernumber','enginesize','fuelsystem','boreratio','stroke','compressionratio','horsepower','peakrpm','citympg','highwaympg','price']]

Empty DataFrame
Columns: [enginetype, cylindernumber, enginesize, fuelsystem, boreratio, stroke, compressionratio, horsepower, peakrpm, citympg, highwaympg, price]
Index: []

In [52]:
df1.cylindernumber.unique()

array([], dtype=object)

In [53]:
#--------8------do group by=---------
# 			enginelocation	enginetype	cylindernumber	price--overall price

In [56]:
df_g=df_car_proj [['enginelocation','enginetype','cylindernumber','price']]
df_g

    enginelocation enginetype cylindernumber      price
3            front        ohc           four  13950.000
4            front        ohc           five  17450.000
5            front        ohc           five  15250.000
6            front        ohc           five  17710.000
7            front        ohc           five  18920.000
8            front        ohc           five  23875.000
9            front        ohc           five  17859.167
10           front        ohc           four  16430.000
11           front        ohc           four  16925.000
12           front        ohc            six  20970.000
14           front        ohc            six  24565.000
15           front        ohc            six  30760.000
16           front        ohc            six  41315.000
89           front        ohc           four   5499.000
90           front        ohc           four   7099.000
91           front        ohc           four   6649.000
92           front        ohc           four   6849.000
93           front        ohc           four   7349.000
94           front        ohc           four   7299.000
95           front        ohc           four   7799.000
96           front        ohc           four   7499.000
97           front        ohc           four   7999.000
98           front        ohc           four   8249.000
99           front        ohc           four   8949.000
100          front        ohc           four   9549.000
101          front       ohcv            six  13499.000
102          front       ohcv            six  14399.000
103          front       ohcv            six  13499.000
104          front       ohcv            six  17199.000
105          front       ohcv            six  19699.000
106          front       ohcv            six  18399.000

In [57]:
df5=df_g.groupby(['enginelocation','enginetype','cylindernumber','price']).count()

In [58]:
df5

Empty DataFrame
Columns: []
Index: [(front, ohc, five, 15250.0), (front, ohc, five, 17450.0), (front, ohc, five, 17710.0), (front, ohc, five, 17859.167), (front, ohc, five, 18920.0), (front, ohc, five, 23875.0), (front, ohc, four, 5499.0), (front, ohc, four, 6649.0), (front, ohc, four, 6849.0), (front, ohc, four, 7099.0), (front, ohc, four, 7299.0), (front, ohc, four, 7349.0), (front, ohc, four, 7499.0), (front, ohc, four, 7799.0), (front, ohc, four, 7999.0), (front, ohc, four, 8249.0), (front, ohc, four, 8949.0), (front, ohc, four, 9549.0), (front, ohc, four, 13950.0), (front, ohc, four, 16430.0), (front, ohc, four, 16925.0), (front, ohc, six, 20970.0), (front, ohc, six, 24565.0), (front, ohc, six, 30760.0), (front, ohc, six, 41315.0), (front, ohcv, six, 13499.0), (front, ohcv, six, 14399.0), (front, ohcv, six, 17199.0), (front, ohcv, six, 18399.0), (front, ohcv, six, 19699.0)]

In [ ]:
# *********  9 ************
# Filter this data
# cylindernumber	enginesize	fuelsystem	boreratio	stroke	compressionratio	horsepower	peakrpm	citympg	highwaympg	price

In [ ]:
df_car_proj[['cylindernumber','enginesize','fuelsystem','boreratio','stroke','compressionratio','horsepower','peakrpm','citympg','highwaympg','price']]

In [ ]:
#-----****  10 *********
# cylindernumber 123 and overall price

In [ ]:
df_car_proj.cylindernumber.unique()

In [ ]:
df_cy=df_car_proj[df_car_proj['cylindernumber'].isin(['one','two','three'])]
df_cy

In [ ]:
df_cy.cylindernumber.unique()

In [ ]:
df_cy[['cylindernumber','price']]

In [ ]:
#-------11-------------

In [ ]:
#-----------12---Q12		fuelsystem	boreratio-overall	stroke-overall	compressionratio-overall

In [ ]:
df_car_proj[['fuelsystem','boreratio','stroke','compressionratio']]

In [ ]:
# Q13	cylindernumber	horsepower	peakrpm	citympg	highwaympg	price

In [ ]:
df_13=df_car_proj[df_car_proj['cylindernumber'].isin(['one','two','three','four'])]

In [ ]:
df_13

In [ ]:
df_13.cylindernumber.unique()

In [ ]:
df_13[['cylindernumber','horsepower','peakrpm','citympg','highwaympg','price']]

In [ ]:
df_car_proj.columns